### ISSUE TITLE
error: Could not find suitable distribution for Requirement.parse('repositoryhandler>=0.3')

### ISSUE THREAD

**Issue by carlosparadis** [MetricsGrimoire/CVSAnalY#103]
I  am getting the following error when attempting to use python setup.py install on an OS X El Captain. Any thoughts on how to solve this? I am mainly looking for a tool that returns LOC for every commit per file, so if the project is no longer active and someone could redirect me to the portion of code that performs this in CVSAnalY I would appreciate it! 

```
Installed /Users/carlos/anaconda/lib/python2.7/site-packages/cvsanaly2-2.1.0-py2.7.egg
Processing dependencies for cvsanaly2==2.1.0
Searching for repositoryhandler>=0.3
Reading https://pypi.python.org/simple/repositoryhandler/
Couldn't find index page for 'repositoryhandler' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for repositoryhandler>=0.3
error: Could not find suitable distribution for Requirement.parse('repositoryhandler>=0.3')
```

**Comment by gregoriorobles** [comment]
Hi,

  you can/should install from the sources:

git clone https://github.com/MetricsGrimoire/RepositoryHandler.git
cd RepositoryHandler
(sudo) python setup.py install

  regards, Gregorio

2016-04-18 10:25 GMT+02:00 Carlos Andrade notifications@github.com:

> I am getting the following error when attempting to use python setup.py
> install on an OS X El Captain. Any thoughts on how to solve this? I am
> mainly looking for a tool that returns LOC for every commit per file, so if
> the project is no longer active and someone could redirect me to the
> portion of code that performs this in CVSAnalY I would appreciate it!
> 
> Installed /Users/carlos/anaconda/lib/python2.7/site-packages/cvsanaly2-2.1.0-py2.7.egg
> Processing dependencies for cvsanaly2==2.1.0
> Searching for repositoryhandler>=0.3
> Reading https://pypi.python.org/simple/repositoryhandler/
> Couldn't find index page for 'repositoryhandler' (maybe misspelled?)
> Scanning index of all packages (this may take a while)
> Reading https://pypi.python.org/simple/
> No local packages or download links found for repositoryhandler>=0.3
> error: Could not find suitable distribution for Requirement.parse('repositoryhandler>=0.3')
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/MetricsGrimoire/CVSAnalY/issues/103

## 

Gregorio Robles
Universidad Rey Juan Carlos
http://gsyc.urjc.es/~grex

**Comment by carlosparadis** [comment]
Hey @gregoriorobles, thank you for the very quick response. That was a silly mistake on my part. It runs just fine now. I have one more question, but since it is unrelated I will open another issue and close this one.
