### ISSUE TITLE
Package repositoryhandler was not found

### ISSUE THREAD

**Issue by franziska-haaf** [MetricsGrimoire/CVSAnalY#106]
Hey guys,

I try to use the programm on 'Oracle VM VirtualBox' in an 'Ubuntu (64-bit) 16.04 LTS'.
I am not a big linux-pro, so i googled most of what i have to do.

First I downloaded  CvsAnalY and the RepositoryHandler.

Than i installed the RepositoryHandler with`sudo python setup.py install` (installed in  `/usr/local/lib/python2.7/dist-packages/repositoryhandler` ).

I set the environment variable with `export PKG_CONFIG_PATH=/usr/local/lib/python2.7/repositoryhandler`.

Than i realised that there is no 'repositoryhandler.pc' file and googled what the f**\* it even is.
I got to [https://lists.libresoft.es/pipermail/metrics-grimoire/2011-November/001959.html](https://lists.libresoft.es/pipermail/metrics-grimoire/2011-November/001959.html) and created the repositoryhandler.pc file with `touch repositoryhandler.pc` in the install-path `/usr/local/lib/python2.7/dist-packages/repositoryhandler`.

Than i searched for the attachment, the guy tells about in his email and found it [http://lists.libresoft.es/pipermail/metrics-grimoire/attachments/20111127/a2547d2f/attachment.asc](http://lists.libresoft.es/pipermail/metrics-grimoire/attachments/20111127/a2547d2f/attachment.asc)
I wrote the same lines into my repositoryhandler.pc file.

But still, when I wanna install cvsanaly, it tells me that the repositoryhandler package was not found... 
I am really annoyed by now, so it would be great, if you can help me ;) 

Thanks a lot,

Franziska

**Comment by franziska-haaf** [comment]
Btw `pkg-config --list-all` shows that i knows repositoryhandler

**Comment by sduenas** [comment]
Hi,

can you open a Python interpreter (i.e ipython) in your terminal, run the next code and put the output here.

First, run this (it should fail):

```
import repositoryhandler
print(repositoryhandler.__file__)
```

Next, run the next statements:

```
import sys
print(sys.path)
```

**Comment by franziska-haaf** [comment]
I created a test.py file and executed it with `python test.py`
The first statements returned:
`/usr/local/lib/python2.7/dist-packages/repositoryhandler/__init__.pyc`
So no fail.

The second statements:
`['/home/franni/Downloads', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']`

**Comment by sduenas** [comment]
That means Python interpreter can find the library so the problem is anywhere else.

> I set the environment variable with export PKG_CONFIG_PATH=/usr/local/lib/python2.7/repositoryhandler.

Mmmm. Why did you do this? After installing Repository Handler you tried to install CVSAnalY and it didn't work? I think this is only useful in some cases. In most of the cases just installing repositoryhandler first and then cvsanaly should work.

Btw, I thik this variable should point to `/usr/local/lib/python2.7/dist-packages/repositoryhandler` not to `/usr/local/lib/python2.7/repositoryhandler` as you wrote. Maybe it was just a typo. Check it please.

In any case, if it doesn't work, try to comment [line number 73](https://github.com/MetricsGrimoire/CVSAnalY/blob/master/setup.py#L73) on `setup.py` file of CVSAnalY and run again the setup command. You can comment the line putting a #  at the beginning of the line.

**Comment by franziska-haaf** [comment]
When i tried to install CVSAnalY after installing the RepositoryHandler i got an error
`Package repositoryhandler was not found in the pkg-config search path.
Perhabs you should add the directory containing 'repositoryhandler.pc' to the PKG_CONFIG_PATH environment variable
No package 'repositoryhandler' found`

Oh and yes, it was an typo :) it is `/usr/local/lib/python2.7/dist-packages/repositoryhandler`

**UPDATE**: I solved my problem! i think i had some kind of an old version of cvsanaly. I was confused because the line 73 was missing. Strange, i have no clue how i got an old version... i am pretty sure i cloned it from github. 
I deleted the folder, cloned it (again) and now the installing is working.
Thank you very much for your fast help! :)

**Comment by sduenas** [comment]
Cool! Nice to hear. You're welcome.
