### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by benmishkanian** [MetricsGrimoire/CVSAnalY#107]
I tried to run this on Windows 10 x64 with Python 2.7 .13, and it does not work. I tried to fix it myself but it seems there are multiple issues. The first error was that cvsanaly2 depends on environment variable $HOME which is not necessarily defined on Windows. After defining that manually, it always says my repository "doesn't seem to point to a repository supported by cvsanaly" even though it is definitely a git repository. The error seems to be caused by a failure to call Popen, caused by Windows not properly supporting close_fds=True. After fixing this, I ran into the error "(10093, 'Either the application has not called WSAStartup, or WSAStartup failed').

Can someone help fix this? I ran cvsanaly on Ubuntu earlier this year and it worked.

**Comment by jgbarah** [comment]
As far as I know, there are no plans to support Windows. Pull requests are welcome, as long as they don't break Linux-like (well, maybe Unix-like) systems, that have always been our reference platform. Sorry about that, most of us don't even have a Windows box handy.

**Comment by benmishkanian** [comment]
Thanks for your response. I might submit some PRs to help with it if I have
the time.

**Comment by jgbarah** [comment]
Thanks a lot! I'm closing this for now, then.
