### ISSUE TITLE
Error runnig libcvsanaly2 generation script

### ISSUE THREAD

**Issue by ricardogarfe** [MetricsGrimoire/CVSAnalY#14]
## Output error

``` shell
Traceback (most recent call last):
  File "~/projects/git/libcvsanaly2/scripts/generations.py",
 line 3, in <module>
    import Numeric
ImportError: No module named Numeric
```
## Run command

``` shell
python generations.py --db-output-user root --db-output-password admin 
--db-output-hostname localhost --db-output-database git_scm_log 
--db-driver mysql --db-user root --db-password admin --db-hostname
 localhost --db-database git_scm_log --db-driver mysql
```
## Environment
- MetricsGrimoire repository master branch
- [libcvsanaly2 master branch](http://git.libresoft.es/libcvsanaly2/).
- Python 2.7
- MySQL Ver 14.14 Distrib 5.5.29
- Ubuntu 12.04

**Comment by ricardogarfe** [comment]
Add the patch using gists to solve issues #14, #15, #16, #17, #18 and #19 

https://gist.github.com/ricardogarfe/4957332

**Comment by andygrunwald** [comment]
New mailinglist post to fix this finally: https://lists.libresoft.es/pipermail/metrics-grimoire/2013-August/002234.html

**Comment by andygrunwald** [comment]
As far as i know (and remember our talk @ FOSDEM 2014) the libcvsanaly2 are deprecated and should not be used anymore.
This is the reason why i close this issue.
If you need this scrips anyway @ricardogarfe has posted how to fix this in https://github.com/MetricsGrimoire/CVSAnalY/issues/14

**Comment by rodrigoprimo** [comment]
@andygrunwald I found this issue while looking for more information about libcvsanaly2. If it is deprecated and should not be used anymore, maybe it is a good a idea to remove the reference to it in CVSAnalY Readme.md (https://github.com/MetricsGrimoire/CVSAnalY/blob/master/README.md) file or add a warning there? Are there alternatives available?
