### ISSUE TITLE
Error runnig libcvsanaly2 fm3 script

### ISSUE THREAD

**Issue by ricardogarfe** [MetricsGrimoire/CVSAnalY#16]
## Output error

``` shell
Traceback (most recent call last):
  File "~/projects/git/libcvsanaly2/scripts/fm3.py",
 line 7, in <module>
    from libcvsanaly2.Exporter import Exporter
ImportError: No module named Exporter

```
## Run command

``` shell
python fm3.py --db-output-user root --db-output-password admin
 --db-output-hostname localhost --db-output-database git_scm_log
 --db-driver mysql --db-user root --db-password admin --db-hostname
 localhost --db-database git_scm_log --db-driver mysql

```
## Environment
- MetricsGrimoire repository master branch
- [libcvsanaly2 master branch](http://git.libresoft.es/libcvsanaly2/).
- Python 2.7
- MySQL Ver 14.14 Distrib 5.5.29
- Ubuntu 12.04

**Comment by andygrunwald** [comment]
In #14 @ricardogarfe has posted the fix of this ticket.

Mailinglist post: https://lists.libresoft.es/pipermail/metrics-grimoire/2013-January/002090.html
Fix: https://gist.github.com/ricardogarfe/4957332

New mailinglist post to fix this finally: https://lists.libresoft.es/pipermail/metrics-grimoire/2013-August/002234.html

**Comment by andygrunwald** [comment]
As far as i know (and remember our talk @ FOSDEM 2014) the libcvsanaly2 are deprecated and should not be used anymore.
This is the reason why i close this issue.
If you need this scrips anyway @ricardogarfe has posted how to fix this in https://github.com/MetricsGrimoire/CVSAnalY/issues/14
