### ISSUE TITLE
Error runnig libcvsanaly2 ltools script

### ISSUE THREAD

**Issue by ricardogarfe** [MetricsGrimoire/CVSAnalY#19]
## Output error

``` shell
Traceback (most recent call last):
  File "~/projects/git/libcvsanaly2/scripts/ltools.py",
 line 50, in <module>
  gfx.render ("ltools-top-commits.png", 500, 400, dataset, options)
  File "~/projects/git/libcvsanaly2/libcvsanaly2/Graphs/PychaGraph.py",
 line 37, in render
    gfx = self.chart (surface, options)
  File "/usr/local/lib/python2.7/dist-packages/pycha-0.6.0-py2.7.egg/pycha/bar.py",
 line 26, in __init__
    super(BarChart, self).__init__(surface, options, debug)
  File "/usr/local/lib/python2.7/dist-packages/pycha-0.6.0-py2.7.egg/pycha/chart.py",
 line 56, in __init__
    self.options.merge(options)
  File "/usr/local/lib/python2.7/dist-packages/pycha-0.6.0-py2.7.egg/pycha/chart.py",
 line 785, in merge
    self[key].merge(other[key])
  File "/usr/local/lib/python2.7/dist-packages/pycha-0.6.0-py2.7.egg/pycha/chart.py",
 line 782, in merge
    for key, value in other.items():
AttributeError: 'str' object has no attribute 'items'


```
## Run command

``` shell
python ltools.py --db-user root --db-password admin
 --db-hostname localhost --db-database git_scm_log --db-driver mysql
```
## Environment
- MetricsGrimoire repository master branch
- [libcvsanaly2 master branch](http://git.libresoft.es/libcvsanaly2/).
- Python 2.7
- MySQL Ver 14.14 Distrib 5.5.29
- Ubuntu 12.04

**Comment by andygrunwald** [comment]
In #14 @ricardogarfe has posted the fix of this ticket.

Mailinglist post: https://lists.libresoft.es/pipermail/metrics-grimoire/2013-January/002090.html
Fix: https://gist.github.com/ricardogarfe/4957332

New mailinglist post to fix this finally: https://lists.libresoft.es/pipermail/metrics-grimoire/2013-August/002234.html

**Comment by andygrunwald** [comment]
As far as i know (and remember our talk @ FOSDEM 2014) the libcvsanaly2 are deprecated and should not be used anymore.
This is the reason why i close this issue.
If you need this scrips anyway @ricardogarfe has posted how to fix this in https://github.com/MetricsGrimoire/CVSAnalY/issues/14
