### ISSUE TITLE
Using a Git library?

### ISSUE THREAD

**Issue by linzhp** [MetricsGrimoire/CVSAnalY#29]
CVSAnalY is using repositoryhandler to parse the output of git command. My impression is that the output format of git command is slightly different in different version of git, which may break CVSAnalY. [This post](http://stackoverflow.com/a/1479669) lists several Python Git modules. They may be more independent on the output format of git command.

**Comment by andygrunwald** [comment]
Hey @linzhp,

good catch!
But i think we have to move RepositoryHandler to a git library, because make sense to provide an interface for all SCMs like repository handler.
What do you think? Does it make sense to move this issue to RepositoryHandler?

**Comment by linzhp** [comment]
Agreed. Let me close this one and open another one in RepositoryHandler

**Comment by andygrunwald** [comment]
Thanks! You will open a new one? This would be great!
