### ISSUE TITLE
Failed to generate Metrics on git repository

### ISSUE THREAD

**Issue by iKuba** [MetricsGrimoire/CVSAnalY#30]
Hello I am trying to generate all metrics of an eclipse git project.

I am executing the following command:

cvsanaly2 -u root -p password --metrics-all

This returns the following output:

Parsing log for /root/org.eclipse.e4.tools (git)
Warning: Detected empty branch 'pwebster/start_421', it'll be ignored
Warning: Detected empty branch 'integration', it'll be ignored
Warning: Detected empty branch 'R4_1_maintenance', it'll be ignored
Executing extensions

This executes in around 5 seconds and when I check my DB there does not seem to be any metric data being generated.

Am I using the wrong command or is this broken? I have looked for documentation on this and there doesn't seem to be much.

Thanks in advance for your help!

**Comment by sduenas** [comment]
To execute extensions you have to add --extensions param to the command. With this param you can set which extensions you want to execute. For your case, the command is:

cvsanaly2 -u root -p password --extensions Metrics --metrics-all

**Comment by iKuba** [comment]
I see, thank you very much for the quick response!
