### ISSUE TITLE
AttributeError: MetricsJob instance has no attribute 'measures'

### ISSUE THREAD

**Issue by mniemela** [MetricsGrimoire/CVSAnalY#88]
I got this error when running CVSAnaly with Metrics to a repository:

  File "/usr/local/lib/python2.7/dist-packages/cvsanaly2-2.1.0-py2.7.egg/pycvsanaly2/extensions/Metrics.py", line 665, in get_measures
    return self.measures
AttributeError: MetricsJob instance has no attribute 'measures'

**Comment by andygrunwald** [comment]
Hey @mniemela, can you port your command you try to execute?
Thanks.

**Comment by mniemela** [comment]
This is the command I'm trying to execute:

cvsanaly2 -u cvsanaly -p cvsanaly --extensions=CommitsLOC,FileTypes,Metrics

Also, this is the repository I'm using for testing:

https://github.com/nathanmarz/storm

**Comment by mniemela** [comment]
Looks like I screwed up in my previous bug fix ( https://github.com/MetricsGrimoire/CVSAnalY/pull/87 ), which could result in MetricsJob not having 'measures' attribute if there's no path for the commit. I fixed this by moving creating the 'measures' attribute a few rows earlier in the code. I created a new pull request for this fix: https://github.com/MetricsGrimoire/CVSAnalY/pull/90

**Comment by andygrunwald** [comment]
This is fixed by #90
