### ISSUE TITLE
Error message wrongly raised: "Invalid extension Weeks"

### ISSUE THREAD

**Issue by dicortazar** [MetricsGrimoire/CVSAnalY#9]
When installing CVSAnalY from scratch and not all of the libraries and dependencies are installed, for specific extensions ("Months" and "Weeks") the "Invalid extension Weeks" (or Months) is raised.

To re-try this bug, please do not install the library to connect python and sqlite: python-pysqlite2. Then if CVSAnalY is run with the following options: "cvsanaly2 --db-user=xxx --db-password=xxx --db-database=xxx --no-parse --extensions=Weeks this will not work.

Thus, there is an error and one improvement:
- Error: In first place, change the message error (it does not make sense to use Invalid Extension when the actual error is another one
- Improvement: Indicate in a list of dependencies also this library

**Comment by andygrunwald** [comment]
I can reproduce this error.

**Comment by andygrunwald** [comment]
I`ve created a small improvement for this errormessage.
@dicortazar maybe you has some time to have a look at it?

**Comment by andygrunwald** [comment]
Now a more useful error message will be deployed. #9 was merged.
