### ISSUE TITLE
RepositoryHandler not found

### ISSUE THREAD

**Issue by falahat** [MetricsGrimoire/CVSAnalY#96]
Upon running python setup.py install, I received this error: 

"error: Could not find suitable distribution for Requirement.parse('repositoryhandler>=0.3')"

It was fixed when I manually installed repositoryhandler. One solution could be to make repositoryhandler listed as a prerequisite or be automatically installed.

**Comment by andygrunwald** [comment]
Thanks @Aryan-Barbarian.
There are several ways to install RepositoryHandler.
You can clone the repository as well and put this path into your $PYTHONPATH-Env variable.

Or you can install it as you did.

If you want to improve the product, feel free to make a Pull Request :)
